spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springjpatest
    username: postgres
    password: 1235
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
